KusionStack/vscode-kusion

- package.json
- src/commands.ts
- src/extension.ts
- src/tasks.ts
re #1 
src/commands.ts
src/extension.ts
src/tasks.ts
package.json
combine preview and apply command to one
```release-note
combine the "Kusion: Preview" and the "Kusion: Apply" command into a single command: "Kusion: Preview Live Diff and Apply"
```
> combine preview and apply command

- Makefile
add make package script to build a vsix for local varification
> add make package script

- package-lock.json
- package.json
- src/commands.ts
- src/extension.ts
- src/quickstart/minikube.ts
- src/quickstart/setup.ts
- src/tasks.ts
provide a quick-start friendly hint(only for quick start use):
- after extension activated: 
- automatically check minikube status and show progress notification; 
- if minikube is not running, automatically process start minikube;
- before trigger preview/apply:
- check the minikube status and if minikube is not ready, show warning notification
> provide quick start friendly hint

- src/extension.ts
- src/tasks.ts
> minor fix: lint code

- package.json
package.json
use category to group commands, as vs code extension convention.
```release-note
None
```
> fix: use category to group kusion commands

- .gitignore
- CHANGELOG.md
- images/preview-dark.svg
- images/preview-light.svg
- package-lock.json
- package.json
- src/commands.ts
- src/extension.ts
- src/preview.ts
- src/util.ts
re #3 
src/commands.ts
src/extension.ts
src/preview.ts
src/util.ts
package-lock.json
package.json
images/preview-dark.svg
images/preview-light.svg
support stack output data preview in yaml format. Can be triggered by Command Palette or the preview button in the editor title.
```release-note
support Stack output data preview.
```
> support stack output data preview in yaml format

- src/preview.ts
- src/util.ts
> feat: preview stack data: add error information when compile failed

- src/quickstart/minikube.ts
- src/util.ts
port-forward: random port and auto rotation for used ports
```release-note
- support random port and used ports rotation when auto port-forward ports;
- prompt to guide users to automatically access the port-forwarded service in the default browser;
```
> Update: port-forward: random port and auto rotation for used ports

- package-lock.json
- package.json
- src/commands.ts
- src/extension.ts
- src/preview.ts
- src/util.ts
re #3 
package-lock.json
package.json
src/commands.ts
src/extension.ts
src/preview.ts
src/util.ts
Enhance/yaml data preview: 
- support yaml highlight in the data preview webview; 
- support switch yaml highlight theme according to the vscode active color theme
- only show preview icon when the active editor file is a KCL file in stack
```release-note
None
```
> Enhance/yaml data preview: support yaml highlight in webview; only show preview icon on KCL file in stack

- package.json
re #29 
package.json
Support auto installation of vscode-kcl extension.
```release-note
None
```
> Support auto installation of vscode-kcl extension

- src/extension.ts
- src/installer.ts
- src/shell.ts
- [Y] Y 
re #29 
src/extension.ts
src/installer.ts
src/shell.ts
support kusion installation detection and prompt to install kusion
```release-note
None
```
> support kusion installation detection and prompt to install

- Makefile
- package.json
Makefile
package.json
fix image path in package.json and add pre-publish script in Makefile
```release-note
None
```
> fix image path in package.json and add pre-publish script in Makefile

- src/commands.ts
- src/installer.ts
- src/preview.ts
always ensure kusion or kcl installed before executing tasks based on them.
```release-note
None
```
> always ensure kusion/kcl installed

- package.json
only show kusion context menu items when current active editor file is in a stack:
we can see that when current file is base.k or server.k, the kusion related context menu is hide.
```release-note
None
```
> add when clause on kusion compile/apply/destroy context menu

- README.md
- package-lock.json
- package.json
> fix vscode version requirement in readme; update to prod version 0.0.10

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- downgrade the dependency version of vscode engines to 1.68.0
- update to prod version 0.0.11
```release-note
None
```
> downgrade the dependency version of vscode engines to 1.68.0

- package-lock.json
- package.json
> update to version 0.0.12

- data/code-city.yaml
- data/deployment-multi-stack.yaml
- data/deployment-single-stack.yaml
- media/create_project.js
- media/reset.css
- media/vscode.css
- package-lock.json
- package.json
- src/commands.ts
- src/create-project.ts
- src/extension.ts
- src/tasks.ts
- src/template-view.ts
- src/utilities/getNonce.ts
- src/utilities/getUri.ts
- src/utilities/getWebviewOptions.ts
> support create project from template

- src/output.ts
- src/template-view.ts
> create project: support generate project files

- CHANGELOG.md
- package-lock.json
- package.json
> pre release 0.0.13

- package.json
- src/commands.ts
- src/extension.ts
- src/installer.ts
- src/livediff.ts
- src/preview.ts
- src/util.ts
> confirm apply: support confirm apply icon

- src/livediff.ts
> live diff: ignore fields: metadata.generation,metadata.managedFields

- media/flow.js
- package-lock.json
- package.json
- src/commands.ts
- src/livediff.ts
- src/operation-view.ts
> confirm apply: support project status webview after confirm apply

- src/template-view.ts
> fix: create from template support stack fields undefined

- src/tasks.ts
> update: skip terminal confirm apply step

- media/flow.js
- src/livediff.ts
- src/operation-view.ts
> update: show project status

- media/flow.js
- src/operation-view.ts
> stack status: support dynamically update status of stacks and resources

- media/create_project.js
- media/flow.js
- src/commands.ts
- src/create-project.ts
- src/extension.ts
- src/installer.ts
- src/livediff.ts
- src/operation-view.ts
- src/preview.ts
- src/quickstart/minikube.ts
- src/quickstart/setup.ts
- src/shell.ts
- src/tasks.ts
- src/template-view.ts
- src/util.ts
- src/utilities/getNonce.ts
> reformat code

- src/livediff.ts
- src/operation-view.ts
> live-diff: show live diff error message

- src/livediff.ts
fix #64 
```release-note
None
```
> fix: live diff preview: refresh diff editor when it is opened before

- src/preview.ts
- src/util.ts
> Update/date preview: remove dependency on kcl and add progress notification

- src/commands.ts
- src/livediff.ts
- src/ocmp.ts
- src/operation-view.ts
src/commands.ts
src/livediff.ts
src/ocmp.ts
src/operation-view.ts
fix broken build: stack project class constructor and wrong import
```release-note
None
```
> fix build: stack project class and wrong import

- package.json
> update: revert default value of kusion templates location settings to []

- media/flow.js
- src/commands.ts
- src/livediff.ts
- src/operation-view.ts
> fix: use stack fullname as kusion command input
